### ISSUE TITLE
Miner Fails to Parse XML When HTTP Response is Compressed or Encoded

### ISSUE THREAD

**Issue by leoloobeek** [PaloAltoNetworks/minemeld-taxii-ng#9]
## Describe the bug

The miner fails to parse indicators from the XML when polling the TAXII server.

## Expected behavior

After polling the server, the XML is parsed, reports success and updates the indicators.

## Current behavior

When polling the server for TAXII data the miner does not parse the XML, reports success, and never adds new indicators.

## Possible solution

When requesting TAXII data from a server that is sending back its response with `Content-Encoding: gzip` the miner is unable to parse the XML. This is due to the use of [requests.Response.raw](https://requests.readthedocs.io/en/latest/api/#requests.Response.raw) which is passed to the XML `iterparse` ([here](https://github.com/PaloAltoNetworks/minemeld-taxii-ng/blob/develop/taxiing/node.py#L305)). The raw data is accessed _before_ the response is GZIP decompressed (as opposed to, for example, [requests.Response.text](https://requests.readthedocs.io/en/latest/api/#requests.Response.text)). 

A simple workaround is to add on `Accept-Encoding: none` or `Accept-Encoding: identity` to request headers. Sample code below for this would start after this [line](https://github.com/PaloAltoNetworks/minemeld-taxii-ng/blob/develop/taxiing/node.py#L291):
```
reqhdrs['Accept-Encoding'] = 'none'
```

## Steps to reproduce

1. Ensure the TAXII server to poll for indicators sends responses back with `gzip` or `compress` content encoding 
2. Add the TAXII miner into MineMeld
3. Ensure the server is started
4. Go to the Nodes tab, select the Miner's name, and select the "run now" button to force a new poll
5. The results should state "Success" but the "# Indicators" will stay at zero

## Context

This prevents us from the ability to retrieve indicators from TAXII servers.

## Your Environment

- minemeld-taxii-ng version 0.1b10
- python 2.7.12

**Comment by jacksiergiej** [comment]
Were you able to resolve the issue with this workaround?  If you could offer any insight as to how you made the changes that would be great.   I tried to copy the code into notepad+ and make the changes, then upload the file to Minemeld, but it complained about the "File should be a python wheel".   

I am new to Minemeld, so and any detailed info you can provide would be helpful!

**Comment by jtschichold** [comment]
I am working on a fix for this

**Comment by jtschichold** [comment]
@leoloobeek I push a new release (0.2a3) that should fix this error. Could you try?

**Comment by hkelley** [comment]
I just tested 0.2a4 and it appears to have fixed the issue.

**Comment by jacksiergiej** [comment]
I tried 0.2a4 and it worked as well now.   My question is that there doesn't seem to be any confidence level attribute on this miner.  A contact at FSISAC mentioned setting up multiple miners, one for each ragw collection.  If I do this, how will the minemeld aggregator know the confidence level of each miner in order to send the info to the correct output location?  

Looking at the logs, I don't see any type of confidence level set of the items.  

I apologize in advance as I am new to Minemeld and learning the product.  Any assistance or insight is GREATLY appreciated!

**Comment by leoloobeek** [comment]
@jtschichold I will close this issue as it appeared to fix the problem. Thanks!
